### ISSUE TITLE
Nade Helper

### ISSUE THREAD

**Issue by EnviousOne** [TheRatCode/RatPoison#300]
Is it possible to have a forums or something where people can upload their nadehelpers files? 
that would help out a lot of people. Also id love to support this creator is there a possible way to do so?

**Comment by TheFuckingRat** [comment]
https://matt1.tk/ratpoison.html Is the only place I know of that has extra nadehelper files, I would suggest the r/csgohacks discord for more, though I doubt many have taken the time to do so. If you want to support the original creator of Charlatano, Jire, his information is at the top of the readme. Id rather you not support myself, unless its something simple like a steam card, and if you want to support @matt1tk you'd have to contact him about anything similar, as he is a new collaborator.

**Comment by Asviix** [comment]
> Is it possible to have a forums or something where people can upload their nadehelpers files?
> that would help out a lot of people. Also id love to support this creator is there a possible way to do so?

I'm currently doing smokes/flashes/Mollies on every map available in Yprac, I'll get to you when it's done.

**Comment by EnviousOne** [comment]
> > Is it possible to have a forums or something where people can upload their nadehelpers files?
> > that would help out a lot of people. Also id love to support this creator is there a possible way to do so?
> 
> I'm currently doing smokes/flashes/Mollies on every map available in Yprac, I'll get to you when it's done.

Awesome! Thank you. much appreciated.

**Comment by mountaincastle47** [comment]
> > > Is it possible to have a forums or something where people can upload their nadehelpers files?
> > > that would help out a lot of people. Also id love to support this creator is there a possible way to do so?
> > 
> > 
> > I'm currently doing smokes/flashes/Mollies on every map available in Yprac, I'll get to you when it's done.
> 
> Awesome! Thank you. much appreciated.

yo bro not yet?
