### ISSUE TITLE
Unbinding?

### ISSUE THREAD

**Issue by misterdoggie** [TheRatCode/RatPoison#315]
I've fiddled around with the settings to what I like, but I've accidentally binded my mouse1 (usually my scope button) to follow targets and I don't know how to unbind it. The menu says I have my trigger key on 2 (mouse 2) but its still invisibly binded to mouse1 and I cant figure out how to unbind it. Whenever I press my mouse1 with my pistol/awp, it fires my gun when it should only scope/do nothing. What should I do?

**Comment by TheFuckingRat** [comment]
What you're wanting is somewhat confusing, but it sounds like your force aim key is on mouse 2, change it somewhere else. Will look into having a menu piece that lays out all the keybinds

**Comment by misterdoggie** [comment]
Sorry, that was kind of confusing haha. My mouse 1 (left mouse button) is basically binded to force/aim shoot even though the menu says its binded to 2 which is supposed to be my mouse 2. Now both mouse 1 and 2 are force aim/shoot and i cant figure out how to unbind mouse 1

**Comment by TheFuckingRat** [comment]
Charlatano had an individual aim key that you would set to be the button you would use to shoot in-game, and force aim is meant to be a key to activate the aimbot without shooting. I don't remember why I hardcoded the aim key to always be mouse 1 but I know there was a reason, and the aim key and force aim key activate the aimbot, the aim key is just meant to shoot along with it. I can add a disable aim key option if there isn't already.
