### ISSUE TITLE
Vac unable to verify game

### ISSUE THREAD

**Issue by EnviousOne** [TheRatCode/RatPoison#319]
So i didnt wanna just post this without testing.

Ive noticed every time i would run the cheat, the game itself would give me that error whenever i would try and search for a match. when i dont run the cheat the game doesnt give me the error. 
only reason its an annoyance is because the only way to fix this is by, verifying game EACH time and opening the cheat AFTER i get into a game.

**Comment by matt1tk** [comment]
Do you have skinchanger enabled? That could be the problem. Skin changers can get vac auth errors (rarely). However this doesn't ban you or anything.

**Comment by EnviousOne** [comment]
this was before i found 1.6 so no skin changer.

**Comment by rawn7702** [comment]
@EnviousOne @matt1tk  I might have a solution for the issue.
So as @TheFuckingRat said that unless the skin changer is turned on the issue won't occur.
So in my case I had my own custom configuration which wouldn't load up when the hacks injects itself into csgo (however it does it). So it loads up the default config instead which might have the skin changer turned on. So I just deleted the default config and replace it with my custom one with skin changer turned off. No vac verify errors anymore.
