### ISSUE TITLE
initializing overlay waiting for app

### ISSUE THREAD

**Issue by duyzz46** [TheRatCode/RatPoison#324]
when i open csgo in fullscreen windowed mode and run the bat file , it just keep saying initializing overlay waiting for app forever, can you help me with this ?
![dfddfsdf](https://user-images.githubusercontent.com/29372985/75886795-65bad780-5e5b-11ea-965e-a74dde9d4780.jpg)

**Comment by matt1tk** [comment]
Try verifying csgo files and rebuilding ratpoison.
