### ISSUE TITLE
VAC can't verify issue

### ISSUE THREAD

**Issue by gigabyte66** [TheRatCode/RatPoison#329]
So I uninstalled RatPoison by deleting the folder (shouldn't have done that ig).
Now, whenever I play CS:GO (also CS:Source), I get the VAC was unable to verify your session issue.
(Link:https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837).

Is something still running in the background or some link that still exits between the cheats and the game?

**Comment by TheFuckingRat** [comment]
I believe @matt1tk mentioned something about the openjdk staying open in the background but I don't remember. Just restart your computer, verify game files, all the standard shit. If you're not using the skin changer you should never get this issue, I don't at least.

**Comment by rawn7702** [comment]
@gigabyte66 I might have a solution for the issue.
So as @TheFuckingRat said that unless the skin changer is turned on the issue won't occur.
So in my case I had my own custom configuration which wouldn't load up when the hacks injects itself into csgo (however it does it). So it loads up the default config instead which might have the skin changer turned on. So I just deleted the default config and replace it with my custom one with skin changer turned off. No vac verify errors anymore.
