### ISSUE TITLE
Fix aimbot with inverted aim

### ISSUE THREAD

**Issue by vsnrytune** [TheRatCode/RatPoison#336]
Would love to use this cheat, but because I'm one of those rare players that play with inverted aim I can't. So please fix <3

Atm. when you have inverted aim enabled, the aimbot starts aiming in the wrong directions so you can't hit anything.

**Comment by Usernameistakensad** [comment]
Try to change the aim method? i think one moves your mouse and one forces it too move in game but im not sure im not da coder xd
