### ISSUE TITLE
How to change keybinds?

### ISSUE THREAD

**Issue by AnimeniacSimey** [TheRatCode/RatPoison#345]
For some reason, the menu uses numbers rather than the actual keyboard character. Can somebody please help? Thanks!

**Comment by russianhorror** [comment]
If you click on the orange "?" _(located to the right of the number window)_, you will be taken to the site with the designation of virtual-key codes - http://cherrytree.at/misc/vk.htm 
There you can find the decimal value _(number)_ of the desired key _(for example, “F1” = 112, etc)_

You can also use https://keycode.info/ for that _(more user-friendly, just tap on key and get the number)_
