### ISSUE TITLE
Only GlowEsp

### ISSUE THREAD

**Issue by toothy36** [TheRatCode/RatPoison#350]
For me at the beginning alot was already turned on and some stuff off, i turned everything off because i only want a wallhack (like box or Skeleton) and Radar hack, since charlatano Always bin good asf i want to use this one. Everything worked in the beginning till i turned everything off than the wallhack stuff, now only GlowEsp works, also only when i look at the enemy, Nothing else is working. halp

edit: * except the wallhack stuff

**Comment by Zayoe4** [comment]
can you send a screenshot of the issue your having. One screenshot of the menu, and another of the actual game.
