### ISSUE TITLE
Suggestion: forcing datacenters

### ISSUE THREAD

**Issue by creepcc** [TheRatCode/RatPoison#351]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/381959-forcing-datacenter.html 
This here seems pretty nice, maybe a field in misc/options where we can toggle force datacenters and pick the datacenter we want

**Comment by matt1tk** [comment]
I'll look into it.

**Comment by Zayoe4** [comment]
What does that do exactly, I'm guessing you can lower ping depending on what datacenter you pick

**Comment by matt1tk** [comment]
It force selects certain servers if for example you wanted to troll south asians (not sure why you'd want to do that)
