### ISSUE TITLE
Game crashes once I enter an online game/FPS drops

### ISSUE THREAD

**Issue by BawnChawn** [TheRatCode/RatPoison#360]
I was messing around with the settings in a bot match and i noticed while the hack worked my fps was very low. Also every time I tried going into an online game my game would crash within 30 seconds.

**Comment by BawnChawn** [comment]
Interestingly enough as i Posted this i tried one more time and it didn't crash! Although my frames were still very choppy

**Comment by sam-ui** [comment]
as per a common fix, try lowering openGL fps to 30, that should reduce the load on the CPU
