### ISSUE TITLE
Automatic shooting shoots through steam overlay

### ISSUE THREAD

**Issue by sotakoira** [TheRatCode/RatPoison#364]
While 1.7 beta fixed shooting through buy menu, you can still shoot through steam overlay. If you also somehow aim at a target while being in steam overlay mouse position will be adjusted with each click (0:33 in the video).

https://streamable.com/jomhaa

**Comment by reviter** [comment]
Hi bro sotakoira, where can I download 1.7 beta version? thank you

**Comment by sotakoira** [comment]
> Hi bro sotakoira, where can I download 1.7 beta version? thank you

https://github.com/TheFuckingRat/RatPoison/tree/beta
clone or download -> download zip
then unpack it and run build.bat file
