### ISSUE TITLE
stuck at launchin... 

### ISSUE THREAD

**Issue by celestial077** [TheRatCode/RatPoison#367]
i did everything.. when launched it says launching and just never launches
what to do?

**Comment by matt1tk** [comment]
run csgo...

**Comment by KiseRyota69** [comment]
my game was running but it was still stuck at 'launching'. waited for an hour, reinstalled but still same.

**Comment by matt1tk** [comment]
Did you install the JDK when it prompted?

**Comment by KiseRyota69** [comment]
I did install one from the java link attached which compiled it and gave errors when running final file. Than I installed when jdk installation prompted, and after that I was stuck at launching.

**Comment by Kauzinn** [comment]
same here, stuck at launching. Installed JDK through the .bat file as instructed, 1920x1080 fullscreen windowed, reinstalled twice with different JDKs, nothing so far

**Comment by KiseRyota69** [comment]
If it has still not worked for you, try right click 'StartRat' and run it as administrator. Worked for me.
