### ISSUE TITLE
"VAC was unable to verify you game session" multiple times because of charlatano.

### ISSUE THREAD

**Issue by effingnoone** [TheRatCode/RatPoison#381]
I know this is ratpoison issue page but it is based on charlatano and author is a Jire supporter so posting it here just for getting a solution because cant find anything on the internet.

"VAC was unable to verify you game session"
I have had this error multiple times in a day. Everytime i verify integrity of game files and restart steam it solves the issue but again after one match (with charlatano on) same error occurs. i even reinstalled steam and csgo but after two matches with chrlatano on again the same error appeared. i am just quitting chralatano for few days till i get some update.
Anyone else havingthis issue or knows something about it?

ps: 1. i know this error has nothing to do with VACban, and i have tried all the methods to fix the error including fresh install of steam and game.
2. this error doesnt occur as long as chralatano is not used after verifying the game files.

**Comment by Boogermonster** [comment]
This could just be because of you CSGO config file. You get this alot when trying to use a PROs config file. Check your config file use default config file and run it.

**Comment by effingnoone** [comment]
i have been using the same config for more than 4 years now man. and its almost default config. do u have any idea what you saying? that doesnt even made sense.

**Comment by Ninjaboy1001** [comment]
This is actually because of your configs. Just delete the CFG folder in your CS:GO Game files and you 
should be good to go.  I had the same issue and doing this fixed it.
