### ISSUE TITLE
Knife changer always gives wrong knife, skin changer often gives random skin

### ISSUE THREAD

**Issue by rpuser999** [TheRatCode/RatPoison#388]
Same issue after reinstallation of everything. Almost all knives are broken (they don't show up or have bugged models) and the ones that do show up are not intended (for example, falchion would pop up whenever I clicked a different one, I believe it was talon)

Also I set a skin on just my AK but I ended up getting a random skin on every other gun too. 

I know the skin changer is new, just providing some feedback that could be looked into

**Comment by Diatro** [comment]
That's because it's not finished and it's supposed to show how it's working.
