### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by brunokakis** [TheRatCode/RatPoison#392]
When pressing F1 the UI windows pop up, but they are blank, no options to choose from. Just blank with gray color. 
![troubleshoot](https://user-images.githubusercontent.com/64965263/81294047-f5a51980-9076-11ea-97b2-931a55ed5e59.png)

**Comment by rpuser999** [comment]
Your menu isn't binding to your game. Try uninstalling any jdk/java stuff you already have on your computer and rebuilding from scratch, but have only the JDK the program prompts you to install
