### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by iSukola** [TheRatCode/RatPoison#393]
![image](https://user-images.githubusercontent.com/21084289/81419997-80594780-914f-11ea-9801-a6de6c8cec89.png)

I'm getting this after a little bit of having the client open. It just shuts down right afterwards.
Happens when changing the toggle aim key VK number and closing the overlay.

EDIT: Happens also when enabling trigger entirely.

**Comment by Ludenife** [comment]
Having the same problem. It happens every time I close the menu window with the close button instead of F1.
