### ISSUE TITLE
Menu extremely zoomed in and leaving behind a gray mask 

### ISSUE THREAD

**Issue by fishjojo1** [TheRatCode/RatPoison#415]
I'm using a 1440p monitor, and running the game on 1920x1080p
Tried this in fullscreen, fullscreen windowed and windowed mode.
(JDK 14)

When I hit F1(the menu key), the cheat menu is extremely zoomed in, and after hitting F1 again, leaves behind a translucent gray screen. Tried changing the res, but to no avail. Has anyone else been encountering this issue?

**Comment by M1XT3NZ** [comment]
Why would you even play on 1080p with a 1440p Monitor that doesn’t make any
sense to me tbh.

Might just be a resolution problem. If it works on 1440p something might
just be a dick.

**Comment by matt1tk** [comment]
Try forcing monitor res to 1080p when using ratpoison/
