### ISSUE TITLE
config legit ratposion

### ISSUE THREAD

**Issue by chackal123** [TheRatCode/RatPoison#452]
has any legit configuration and that kills enough for the league?

**Comment by akmeister** [comment]
Here are my legit settings. No skin changer though.

[ratpoison 1.7.1.1 settings.zip](https://github.com/TheFuckingRat/RatPoison/files/4773109/ratpoison.1.7.1.1.settings.zip)

**Comment by chackal123** [comment]
these settings to play championship? without the visuals

**Comment by akmeister** [comment]
> these settings to play championship? without the visuals

No, just disable chems and glow and you should be fine

**Comment by matt1tk** [comment]
League?... what league anti cheat?

**Comment by chackal123** [comment]
esea, faceit, a config that kills a lot, but doesn’t show off in the face, the visuals I will not use

**Comment by matt1tk** [comment]
Do you really expect a free cheat to work on faceit AC or esea?...

**Comment by chackal123** [comment]
it works for me, with a bypass I bought, but I wanted a legit and good config with this new version 7.1

**Comment by matt1tk** [comment]
I’m not sure if it’ll work safely, but just mess around in aim_botz map
until you think it looks legit.

**Comment by chackal123** [comment]
matt1tk could you pass me your config?

**Comment by matt1tk** [comment]
Mine is default settings with no ESP but radar and chams.
