### ISSUE TITLE
How do I use the Skin Changer? What is KNIFE_IDX

### ISSUE THREAD

**Issue by dacryphiliac** [TheRatCode/RatPoison#453]
I'm doing alright changing the skins themselves, but how do I change my knife and the knife's skin? What is KNIFE_IDX ????

**Comment by TheFuckingRat** [comment]
Knife is disabled and removed from the menu in 1.7, no point changing it at the moment.

**Comment by dacryphiliac** [comment]
> Knife is disabled and removed from the menu in 1.7, no point changing it at the moment.

any plans on readding the feature?
