### ISSUE TITLE
Request: Would you please share the vis-ui skin project

### ISSUE THREAD

**Issue by r0ot7** [TheRatCode/RatPoison#464]
Hey,

I would like improve the UX and change the skin from tinted to may be neon.
Would you please share the skin project so I could tweak it and build it.

Thank you.

**Comment by retart1337** [comment]
https://github.com/TheFuckingRat/RatPoison/tree/beta/skin
???

**Comment by r0ot7** [comment]
> https://github.com/TheFuckingRat/RatPoison/tree/beta/skin
> ???

This is the outcome of the skin project, I meant libgdx project.

**Comment by sidekek** [comment]
this?
https://github.com/kotcrab/vis-ui
