### ISSUE TITLE
All errors i got

### ISSUE THREAD

**Issue by Overman999** [TheRatCode/RatPoison#465]
Overlay errors : - [LWJGL] GLFW_PLATFORM_ERROR error
                           Description : WGL: Failed to make context current: The handle is invalid.

                        - AL lib: (EE) alc_cleanup: 1 device not closed
                          ( then the app close )

When I turn off the overlay i got somtime this error : SetAim failure

Apart from that this cheat is incredible thank you @Jire

**Comment by Overman999** [comment]
oh and i forgot hitsound doesn't work

**Comment by retart1337** [comment]
Try to update OpenGL drivers
