### ISSUE TITLE
BETA. Automatic weapon shooting delay?

### ISSUE THREAD

**Issue by phooooon** [TheRatCode/RatPoison#470]
where is it? it keeps throwing my grenades when i hold down mouse1

**Comment by Overman999** [comment]
It's in miscscripts:

//Enable automatic weapons
//Will attempt to shoot non-automatic weapons based on auto wep delay
AUTOMATIC_WEAPONS = true

//The MS delay between shooting
AUTO_WEP_DELAY = 11

**Comment by phooooon** [comment]
In ratpoison 1.7 there is no text regarding weapon delay
