### ISSUE TITLE
Gets Stuck At Launching

### ISSUE THREAD

**Issue by Blu-2** [TheRatCode/RatPoison#477]
The build part works and i have the jdk installed but it just won't launch in game, it says loading setting settings loaded then gets stuck at launching. Any fixes?

**Comment by keenys** [comment]
i have the same :/

**Comment by retart1337** [comment]
Was fixed in newest versions, redownload from github

**Comment by devdev1120** [comment]
i just downloaded today and im getting loading settings settings loaded then stuck at launching??
