### ISSUE TITLE
just downloaded getting stuck at launching

### ISSUE THREAD

**Issue by devdev1120** [TheRatCode/RatPoison#524]
i keep getting the same message in the command it says Loading settings...
Settings loaded
Launching...
then just stays there 
ive waited a while and tried re downloading but nothing seems to work

**Comment by r0ot7** [comment]
> i keep getting the same message in the command it says Loading settings...
> Settings loaded
> Launching...
> then just stays there
> ive waited a while and tried re downloading but nothing seems to work

Is this the case when CS GO is running already ?
