### ISSUE TITLE
Rage config

### ISSUE THREAD

**Issue by yeetshmeet** [TheRatCode/RatPoison#527]
anybody have some kind of rage or rage like config that I can use?

**Comment by sotakoira** [comment]
yeah there are a lot of them in the discord

**Comment by yeetshmeet** [comment]
Cool can you link the discord I cant find it?

**Comment by sotakoira** [comment]
https://github.com/TheFuckingRat/RatPoison/blob/master/src/main/kotlin/rat/poison/ui/tabs/OptionsTab.kt#L39
