### ISSUE TITLE
[QUESTION] My virus scanner saysit has a trojan virus, why does it doo that?

### ISSUE THREAD

**Issue by RatpoisonUser** [TheRatCode/RatPoison#625]
Is there a virus in this or is it just something else? My question is basically in the title.

**Comment by SPRAVEDLIVO** [comment]
It is because of installer, false-positive. 
Installer is open source, source available on 
https://github.com/SPRAVEDLIVO/RatInstaller

**Comment by RatpoisonUser** [comment]
and how do i download the installer

**Comment by SPRAVEDLIVO** [comment]
it is bundled with rp

**Comment by RatpoisonUser** [comment]
Is there another way to download it other than the installer

**Comment by SPRAVEDLIVO** [comment]
😐 why

**Comment by sotakoira** [comment]
Fork the project, remove installer files (installer.exe, installerSettings.json), add your own building script and download the repository.
It's that easy.

**Comment by RatpoisonUser** [comment]
Im really stupid when programming, cause i cant program, can i just downlaod the script?

**Comment by SPRAVEDLIVO** [comment]
you can get installer from GitHub released, bc its just open source build automatically by github so no potential adding hidden shit

https://github.com/SPRAVEDLIVO/RatInstaller/releases

**Comment by sotakoira** [comment]
You can try modyfing this old build script to work properly with newer versions of RatPoison, I haven't tested it with the newest release available.
https://github.com/TheRatCode/RatPoison/blob/e780753f953b3a4529658b504bd6b120c693582e/build.bat

**Comment by RatpoisonUser** [comment]
I have ratpoison 1.6 can i upgradenit from the files?

**Comment by SPRAVEDLIVO** [comment]
why you can't download 1.7 
and installer from 1.7 and above can update everything easily

**Comment by sotakoira** [comment]
While 1.6 could be technically updated with dropping installer.exe there, it is wiser to just download new version from GitHub.

**Comment by RatpoisonUser** [comment]
I will use downloas it here

**Comment by SPRAVEDLIVO** [comment]
no
