### ISSUE TITLE
[BUG] Doesnt run - error.

### ISSUE THREAD

**Issue by justreathy** [TheRatCode/RatPoison#629]
Heya, when i run the launcher, i get this error, and the hack doesnt run.

>          App Title: Counter-Strike: Global Offensive
>          [DEBUG] Using GL3
>          Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalArgumentException: Error compiling shader: Vertex shader
>          Vertex shader failed to compile with the following errors:
>          ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
>          ERROR: error(#273) 1 compilation errors.  No code generated
> 
>          Fragment shader:
>          Fragment shader failed to compile with the following errors:
>          ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
>          ERROR: error(#273) 1 compilation errors.  No code generated
>          
>          
>         at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:163)
>         at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:126)
>         at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:80)
>         at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:92)
>         at rat.poison.overlay.App.create(App.kt:80)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
>         at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:172)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

thank you.

**Comment by SPRAVEDLIVO** [comment]
Pc specs?

**Comment by justreathy** [comment]
intel core i3, amd radeon hd 6670

Pc specs?

**Comment by SPRAVEDLIVO** [comment]
That seems kinda old, its a common issue that openGL doesn't work on old gpus

**Comment by SPRAVEDLIVO** [comment]
Can't be fixed at this point, closing

**Comment by justreathy** [comment]
so im fucked? :D is there some way to fix it, or smth?

**Comment by SPRAVEDLIVO** [comment]
ye ur fucked
