### ISSUE TITLE
[SUGGESTION]DISCORD Stream Proof

### ISSUE THREAD

**Issue by dayz2000** [TheRatCode/RatPoison#630]
**Describe the feature requested**
A clear description or pictures/videos of what you want implemented.
for discord stream

**Comment by SPRAVEDLIVO** [comment]
dude that tells us nothing

**Comment by SPRAVEDLIVO** [comment]
There is already. Disable all in-game visuals (chams, glow etc.) and enable visuals that are drawn in overlay (box esp, head lvl) and choose to share only CS:GO in discord, not whole screen. If by "Stream Proof" you mean detect when screen is sharing, it wont be added because pretty impossible.
