### ISSUE TITLE
[QUESTION] Can we update it by rebasing master when there is update?

### ISSUE THREAD

**Issue by quentinmrvn** [TheRatCode/RatPoison#641]
**Ask questions**
Ask any questions related to the project

**Comment by SPRAVEDLIVO** [comment]
Why would you need that? Pulling changes from origin is cooler, also i pretty sure that no

**Comment by sotakoira** [comment]
i updated my ratpoison paste with rebase, it requires fuckton of code reviewing. other than that works pretty well

**Comment by SPRAVEDLIVO** [comment]
Closing for now, if you have more questions join discord.
