### ISSUE TITLE
[SUGGESTION] Grenade expiration bars/timers

### ISSUE THREAD

**Issue by sotakoira** [TheRatCode/RatPoison#648]
**Describe the feature requested**
A clear description or pictures/videos of what you want implemented.

Wear off time: Molotov, Smoke
Time to explosion: ~~Decoy~~, HE, Flashbang

Bar and timer being separate toggles.

![csgo_2020-11-20_14-24-01](https://user-images.githubusercontent.com/63243610/99805728-3a892d00-2b3d-11eb-8c92-84f1d2d67039.png)

**Comment by SPRAVEDLIVO** [comment]
source from other external chit or perish

**Comment by sotakoira** [comment]
externals using smoke netvars have only disable smoke feature, this is probably the best source i could find lol
https://github.com/WarezBox/aimware/blob/master/%5BLuaScript%20V5%5D%20Smoke%20timer%20ESP
