### ISSUE TITLE
[BUG] Both force aim and normal aim targeting body, even though they're set to head

### ISSUE THREAD

**Issue by Frappyy** [TheRatCode/RatPoison#650]
So for some reason, the cheat is always targeting and aiming at the body. This is obviously a bug, but how do I get it to aim at the head/neck area?

Probably can't reproduce this as I couldn't find anyone who had the same issue.

**Comment by SPRAVEDLIVO** [comment]
record evidence and send your config

**Comment by sotakoira** [comment]
uid issue, counter evidence:
https://streamable.com/9oy4dl
https://streamable.com/qexmwu

**Comment by SPRAVEDLIVO** [comment]
https://tenor.com/view/csgo-hvh-cheat-gamesense-anti-aim-gif-19054172
