### ISSUE TITLE
[SUGGESTION] SkinChanger for knife and gloves

### ISSUE THREAD

**Issue by TreeV2** [TheRatCode/RatPoison#658]
Can you add skin changer for knife and gloves ? and can you fix i set printstream skin to deagle but in hud the text wasn t show only if i drop the gun and pick up again. here video:  https://streamable.com/n3m87l

**Comment by sotakoira** [comment]
#645

**Comment by TreeV2** [comment]
but can you fix the bug ?

**Comment by SPRAVEDLIVO** [comment]
enable force update

**Comment by TreeV2** [comment]
i have enabled force update

**Comment by SPRAVEDLIVO** [comment]
its not supposed to work like that

**Comment by SPRAVEDLIVO** [comment]
tldr working as intended
