### ISSUE TITLE
[QUESTION]AIMBOT

### ISSUE THREAD

**Issue by TreeV2** [TheRatCode/RatPoison#660]
Why my aimbot sometimes self disable  ?

**Comment by TreeV2** [comment]
I think skin changer disable my aimbot

**Comment by sotakoira** [comment]
default toggle aimbot key is f3, that is also default key for auto buy, probably that's why you are getting it disabled

**Comment by TreeV2** [comment]
I don t think so because my aimbot disable in mid game

**Comment by SPRAVEDLIVO** [comment]
😐 tf cheese

**Comment by SPRAVEDLIVO** [comment]
Works fine for others, remember that aimbot is not based on recoil position, might be fov issue, try to make config with big ass fov and see how it works with bots.

**Comment by TreeV2** [comment]
I think skin changer disable my aimbot

**Comment by SPRAVEDLIVO** [comment]
there is no reason skinchanger would do this

**Comment by SPRAVEDLIVO** [comment]
how is your aimbot disabled? like it is disabled as option in menu or you feel like it doesn't help you to aim?

**Comment by TreeV2** [comment]
in option menu

**Comment by SPRAVEDLIVO** [comment]
😐 try to set it to -1 and see if shit changes

**Comment by SPRAVEDLIVO** [comment]
by it i mean toggle aim key

**Comment by TreeV2** [comment]
ok

**Comment by SPRAVEDLIVO** [comment]
Seems to be resolved. Closing
