### ISSUE TITLE
Overlay 

### ISSUE THREAD

**Issue by Tenseleo** [TheRatCode/RatPoison#666]
The overlay on csgo doesnt pop up even tho im windowed or running java jdk 1.14

**Comment by SPRAVEDLIVO** [comment]
Have you changed your resolution to fullscreen windowed?

**Comment by SPRAVEDLIVO** [comment]
any errors in console?

**Comment by SPRAVEDLIVO** [comment]
if you are using beta, menu key was changed to insert

**Comment by Tenseleo** [comment]
> 
> 
> any errors in console?

No it just sais overlay initialized and yes its in fullscreen windowed

**Comment by Tenseleo** [comment]
> 
> 
> if you are using beta, menu key was changed to insert

No im not using a beta version

**Comment by SPRAVEDLIVO** [comment]
try pressing f1

**Comment by Tenseleo** [comment]
> 
> 
> try pressing f1

tried nothing pops up

**Comment by Tenseleo** [comment]
not even the spec list or the time for the bomb

**Comment by SPRAVEDLIVO** [comment]
try beta

**Comment by Tenseleo** [comment]
> 
> 
> try beta

How ? if you dont mind

**Comment by SPRAVEDLIVO** [comment]
https://github.com/TheRatCode/RatPoison/releases/tag/1.8.4

**Comment by Tenseleo** [comment]
> 
> 
> https://github.com/TheRatCode/RatPoison/releases/tag/1.8.4

thanks have a great day

**Comment by Tenseleo** [comment]
> 
> 
> https://github.com/TheRatCode/RatPoison/releases/tag/1.8.4

still same problem sorry if im bothering you with that

**Comment by SPRAVEDLIVO** [comment]
what about pressing insert?

**Comment by Tenseleo** [comment]
> 
> 
> what about pressing insert?
Sorry but how do i do that?

**Comment by SPRAVEDLIVO** [comment]
do you know where insert button is located?

**Comment by Tenseleo** [comment]
> 
> 
> do you know where insert button is located?

i do

**Comment by SPRAVEDLIVO** [comment]
try to press it

**Comment by Tenseleo** [comment]
while im selecting the file?

**Comment by SPRAVEDLIVO** [comment]
run the .bat file and press insert in csgo

**Comment by Tenseleo** [comment]
the INS button on my keyboard?

**Comment by SPRAVEDLIVO** [comment]
ye

**Comment by Tenseleo** [comment]
so i run the bat. file and press ins ?

**Comment by SPRAVEDLIVO** [comment]
run the bat file, alt tab to csgo and press ins

**Comment by Tenseleo** [comment]
> 
> 
> run the bat file, alt tab to csgo and press ins

It worked thank you
