### ISSUE TITLE
crashes when i start to shoot

### ISSUE THREAD

**Issue by suciuale** [TheRatCode/RatPoison#679]
i use this config 
[Legit - Copy.txt](https://github.com/TheRatCode/RatPoison/files/5715079/Legit.-.Copy.txt)

when i try to shoot the enemy, the game crashes. I'll try different settings

**Comment by suciuale** [comment]
tried to play without aimbot, same situation

**Comment by SPRAVEDLIVO** [comment]
https://github.com/TheRatCode/RatPoison/issues/676
Redownload and recompile beta branch.
