### ISSUE TITLE
Ratpoison Black Screen. I looked at topics 136 and 147, did not help.

### ISSUE THREAD

**Issue by KoJloxyceHka** [TheRatCode/RatPoison#688]
Hello. Downloaded this Ratpoison.
Java SE Development Kit 15 installed.
I did everything exactly according to the instructions, but something seems to be wrong. The menu works, everything turns on and off. But why is it a black screen. I tried to study topics **136** and **147**, but apparently I'm not smart enough) in variable environments, I put it on Java / Bin. And to raise to the very top, but that did not help.
I also put the game in full-screen mode. And in the window. I also launched the cheat with administrator rights, because without them, it does not work at all. Please who can help me. By the way, cheat Charlatano, it works for me properly. And the Ratpoison cheat doesn't work. Thanks in advance. And excuse my English, I use Google translator, as I live in Ukraine.
![Безымянный](https://user-images.githubusercontent.com/76458164/102836779-f2428080-4402-11eb-8348-e73f35674ea7.png)
![Безымянный](https://user-images.githubusercontent.com/76458164/102837336-426e1280-4404-11eb-9a57-7429d363ca60.png)

**Comment by sotakoira** [comment]
https://github.com/TheRatCode/RatPoison/releases/download/1.7.1.1/RatPoison-1.7.1.1.zip
https://github.com/TheRatCode/RatPoison/releases/download/1.8.4/RatPoison-1.8.4.zip
Either one of those should work if you want a quick way to run the cheat without really thinking about the problem.

Otherwise make sure 
![SystemPropertiesAdvanced_2020-12-22_02-11-32](https://user-images.githubusercontent.com/63243610/102836963-0c786080-43fb-11eb-9721-15ec35df3013.png)
and
![firefox_2020-12-22_02-12-20](https://user-images.githubusercontent.com/63243610/102837007-2ade5c00-43fb-11eb-9f3b-4ed076f79567.png)
variables are set like this, you can google the problem further.

**Comment by KoJloxyceHka** [comment]
**@sotakoira** 
Hello again. I did everything exactly as you suggested to me, and on the Internet I looked how to correct Java libraries in variable environments. Nothing helped. Unfortunately.

**> https://github.com/TheRatCode/RatPoison/releases/download/1.7.1.1/RatPoison-1.7.1.1.zip
https://github.com/TheRatCode/RatPoison/releases/download/1.8.5/RatPoison-1.8.5.zip**
tried these two versions that you wrote to me in the answer.
in 1.7.1.1. Black screen and the menu on F1 turns on. There are sounds, I can move, etc.
in 1.8.5 just a black screen, the menu does not turn on at all. I can also move and sounds are present.
In variable environments, I wrote everything correctly. Rebooted the computer. And still the same situation. I attach the screenshots.
I do not know what to do. And I run this cheat only with administrator rights, otherwise it is eternal loading.
I probably won't torture you. I am very grateful to you for what you tried to help me.
![Безым23янный](https://user-images.githubusercontent.com/76458164/102913070-ed271500-4486-11eb-9e01-7b07fb016214.png)
![Безымянн43ый](https://user-images.githubusercontent.com/76458164/102913074-edbfab80-4486-11eb-86d5-5884090b13c6.png)
![Безымянный](https://user-images.githubusercontent.com/76458164/102913077-ee584200-4486-11eb-9f67-daec413c7483.png)

**Comment by sotakoira** [comment]
Keep using charlatano then, no way of telling what in your hardware or software is failing to produce this.

**Comment by KoJloxyceHka** [comment]
@sotakoira What should I say? I also have a custom build of Windows 10. With many different tweaks. Perhaps it somehow affects. I do not know. You may need to install a completely clean version of the system.
Anyway, thanks a lot for trying to help me. Good luck.

**Comment by Jire** [comment]
Maybe it has something to do with transparency? Make sure your Windows supports regular transparency functions

**Comment by KoJloxyceHka** [comment]
@Jire 
Transparency works. Everything looks right. Java 15. Java is installed where it needs to be. Libraries, in variable environments, are spelled out correctly. I run it as administrator. But all the same, a black screen and a menu opens. What it might be, I don't understand. I'll probably close the question. Because everything that was suggested to be done does not work.

**Comment by SPRAVEDLIVO** [comment]
Have you changed your gane res to fullscreen-windowed?

**Comment by KoJloxyceHka** [comment]
@SPRAVEDLIVO I tried on the window too. And in full screen. And in full screen in the window.
In full screen, nothing works. When you press F1, the game is minimized.
In the window, a black screen. And the menu opens at F1.
Already tried everything, all the tips and tricks.
Even Windows reinstalled. It still didn't help. Unfortunately, nothing helps.

**Comment by SPRAVEDLIVO** [comment]
It is correct, seems like uid issue and we cant help you in any ways

**Comment by KoJloxyceHka** [comment]
@Jire @SPRAVEDLIVO @sotakoira 
I have 15 Java installed.  JDK.  but no JRE installed.  is it needed or not?  perhaps because of this it does not work.

**Comment by SPRAVEDLIVO** [comment]
> @Jire @SPRAVEDLIVO @sotakoira
> I have 15 Java installed. JDK. but no JRE installed. is it needed or not? perhaps because of this it does not work.

It is not needed and it is recommended to not have it installed at all.
Have you tried running bat without admin, as mentioned in #136 it can be cause of blackscreen

**Comment by SPRAVEDLIVO** [comment]
My final guess:
edit build/RatPoison 1.8.x/start RatPoison 1.8.x
replace "java" on line 5 to your java path, e.g.
``` "C:\Program Files\jdk-15.0.1\bin\java.exe" -Xmx512m -Xms32m -XX:+UseSerialGC -jar "RatPoison 1.8.5.jar" ```

**Comment by KoJloxyceHka** [comment]
**@SPRAVEDLIVO** Greetings! Surprising but true. Looked at your advice. And I decided to try again.
I downloaded RatPoison 1.8.4 (Source code.zip.) I started installing via the installer. And then suddenly this installer opened a new command line window. Via Java 15 which I have installed. When everything was established, I went into cs go. I went to the map, I do not run as administrator, Start RatPoison 1.8.bat. And I didn't understand how, but it worked. There is no black screen, the menu opens and adjusts normally. I don't even know why it suddenly happened. The bat file already contained the path that you advised.
![Безымянный](https://user-images.githubusercontent.com/76458164/103182890-8d31d380-48b7-11eb-98ff-3e49251e8e05.png)

**Comment by SPRAVEDLIVO** [comment]
> **@SPRAVEDLIVO** Greetings! Surprising but true. Looked at your advice. And I decided to try again.
> I downloaded RatPoison 1.8.4 (Source code.zip.) I started installing via the installer. And then suddenly this installer opened a new command line window. Via Java 15 which I have installed. When everything was established, I went into cs go. I went to the map, I do not run as administrator, Start RatPoison 1.8.bat. And I didn't understand how, but it worked. There is no black screen, the menu opens and adjusts normally. I don't even know why it suddenly happened. The bat file already contained the path that you advised.
> **But what about VAC? I understand correctly? Is this cheat not detecting it? And you can't get a VAC for it? The same as for the Charlatano cheat? Only the patrol is dangerous?**
> ![Безымянный](https://user-images.githubusercontent.com/76458164/103182890-8d31d380-48b7-11eb-98ff-3e49251e8e05.png)

it is vac undetected atm, anything can be changed at any time
