### ISSUE TITLE
[SUGGESTION] Bomb and Smoke timer Offsets in beta broken.

### ISSUE THREAD

**Issue by PIKAPIKARY** [TheRatCode/RatPoison#689]
You probably know, but the smoke timer does not always work (it shows a huge number of seconds), and the bomb time is not shown at all. **Hopefully you can update for release.**

**Comment by sotakoira** [comment]
You are using a build that has been moved to alpha. Beta does not have this issue.

https://user-images.githubusercontent.com/63243610/103142634-9596dc80-4706-11eb-9f67-53c0dc8edabe.mp4

**Comment by SPRAVEDLIVO** [comment]
will be resolved eventually by jire

**Comment by thefuckingrap** [comment]
https://user-images.githubusercontent.com/68853992/103142654-c9590e80-46d4-11eb-9cab-8df663cf2346.mp4
