### ISSUE TITLE
Stuck On Lunching

### ISSUE THREAD

**Issue by TheMaevis33** [TheRatCode/RatPoison#690]
I opened debug and it says program can't find csgo I started with adminstration but it didn't worked for me sorry for my bad English I'm waiting for your help thanks

**Comment by TheMaevis33** [comment]
![Capture](https://user-images.githubusercontent.com/76601916/103151068-ba816300-478b-11eb-91a8-1ebc1a9c866f.PNG)
Here is the problem

**Comment by SPRAVEDLIVO** [comment]
![Screenshot_2020-12-26-18-20-12-149_com android chrome](https://user-images.githubusercontent.com/48867150/103154230-13122980-47a7-11eb-9cbf-c9f1e6cf664f.jpg)
