### ISSUE TITLE
[BUG] Automatic weapons tapping issue.

### ISSUE THREAD

**Issue by sotakoira** [TheRatCode/RatPoison#693]
**Describe the bug**

If you start the game in Fullscreen and press Insert you will be thrown out to desktop and upon tabbing into CS:GO you will tap with automatic weapons until you press Insert again.

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

1. Run the game in Fullscreen mode.
2. Run the cheat
3. After running the cheat tab into CS:GO
4. Press the menu key
5. After being tabbed out to desktop, go back into CS:GO
6. Your automatic weapons will now tap until you press menu key again.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

https://streamable.com/wre50c

I know this is more of an UID issue but I see some people having this problem.

**Comment by victorshx** [comment]
This is not a bug, RatPoison is an external cheat.

**Comment by sotakoira** [comment]
> This is not a bug, RatPoison is an external cheat.

Yet you see this problem appearing weekly on discord. People don't know you should use appless or menu false for fullscreen and there's nothing in faq about this exact behavior.

**Comment by SPRAVEDLIVO** [comment]
This line explains this behaviour

https://github.com/TheRatCode/RatPoison/blob/513fbcc120c5fe04f9bd3289b8763a6a29643d1f/src/main/kotlin/rat/poison/scripts/aim/HandleFireKey.kt#L29

This can be solved by adding fullscreen mode detection, good catch

**Comment by victorshx** [comment]
> > This is not a bug, RatPoison is an external cheat.
> 
> Yet you see this problem appearing weekly on discord. People don't know you should use appless or menu false for fullscreen and there's nothing in faq about this exact behavior.

Now I understand what you meant. Sorry for the quick judgment, I thought you meant throwing you to the desktop is a bug.

**Comment by SPRAVEDLIVO** [comment]
> > Yet you see this problem appearing weekly on discord. People don't know you should use appless or menu false for fullscreen and there's nothing in faq about this exact behavior.
> 
> Now I understand what you meant. Sorry for the quick judgment, I thought you meant throwing you to the desktop is a bug.

yeah but it isnt my issue :|

**Comment by victorshx** [comment]
> yeah but it isnt my issue :|
Let me get used to the syntax of Kotlin then maybe I can do some PR for bug fixes and feature improvements. Not a fan of Java, but it stays undetected because of it 😬
