### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Harry-Plays** [TheRatCode/RatPoison#696]
How do you even open the menu

**Comment by SPRAVEDLIVO** [comment]
1.7 - F1
1.8 - Insert

**Comment by dimdenGD** [comment]
sup wyd wya

**Comment by SPRAVEDLIVO** [comment]
> sup wyd wya

https://media.tenor.co/videos/3d4f7f56cb3e61d41b802c44a8d04931/mp4

**Comment by kird3333d** [comment]
1.7 F1
1.8 Ins

**Comment by SPRAVEDLIVO** [comment]
Dont forget to change your resolution to fullscreen windowed
