### ISSUE TITLE
works till you load into a game, it was working yesterday but now when ever i load into a game it just black screens[BUG]

### ISSUE THREAD

**Issue by Zxnna** [TheRatCode/RatPoison#701]
**Describe the bug**

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

**Comment by mountaincastle47** [comment]
I am also experiencing this

**Comment by SPRAVEDLIVO** [comment]
fixed

**Comment by deXyy999** [comment]
also experiencing this
