### ISSUE TITLE
[BUG] Game crashes with 01/08/2021 Update. 

### ISSUE THREAD

**Issue by Ratmanone** [TheRatCode/RatPoison#704]
**Describe the bug**
The game instant crashes on hook.

**To Reproduce**
Run csgo.exe, load cheat.bat, ???? crash..

**Comment by sotakoira** [comment]
Edit [this line](https://github.com/TheRatCode/RatPoison/blob/master/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt#L17) to `val dwbSendPackets = 881610` then recompile.

This should fix itself once [blazedumper](https://github.com/Akandesh/blazedumper) updates again.

**Comment by BlueTiNet** [comment]
The alpha 1.8.5+ doesn't seem to have this problem
