### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Ugly-frostie-411** [TheRatCode/RatPoison#705]
Can you make it so you can build it like 1.7.1 to change the opengl to 3 instead of 4
 cause my gpu doesnt support 4 and ive been using this software since its upbringing and never had an issue with it. until these latest ones with the opengl update you have done an I dont want to go back to using charlatano cause the configing was very tedious.

**Comment by SPRAVEDLIVO** [comment]
https://github.com/TheRatCode/RatPoison/blob/2c18109a101cc1611a6a7502ea9500b010310f1e/src/main/kotlin/rat/poison/RatPoison.kt#L183
