### ISSUE TITLE
[QUESTION] Jumpshot

### ISSUE THREAD

**Issue by jsjsjssffg** [TheRatCode/RatPoison#707]
Is it possible to set jumpshot for example on awp to some 25% effectiveness

**Comment by SPRAVEDLIVO** [comment]
tf it means

**Comment by KreechurCS** [comment]
@jsjsjssffg Are you asking if its possible to make the AWP accurate on a jumpshot 25% of the time? if so then no

**Comment by SPRAVEDLIVO** [comment]
no

**Comment by jsjsjssffg** [comment]
@KreechurCS  thanks for the answer
