### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ugly-frostie-411** [TheRatCode/RatPoison#711]
When I use the cheat it crashes csgo as soon as you start to load into a match im not sure if this is just me or others are having this issue. 
An it only started to happen after this recent update.

**Comment by uwuLegacy** [comment]
die

**Comment by kih** [comment]
delete system32 it fixed it for me

**Comment by Ugly-frostie-411** [comment]
> delete system32 it fixed it for me

bruh you really think im that fucking stupid

**Comment by kih** [comment]
> > delete system32 it fixed it for me
> 
> bruh you really think im that fucking stupid

why else would i tell you that

**Comment by Ugly-frostie-411** [comment]
also I use linux dumb fuck

**Comment by Ugly-frostie-411** [comment]
> > > delete system32 it fixed it for me
> > 
> > 
> > bruh you really think im that fucking stupid
> 
> why else would i tell you that

bro I run in a linux environment

**Comment by sotakoira** [comment]
https://github.com/TheRatCode/RatPoison/issues/704#issuecomment-756658538
but you replace with `val dwbSendPackets = 881642` or just wait for repo to update.
