### ISSUE TITLE
GAME CRASHES

### ISSUE THREAD

**Issue by DenixxBTW** [TheRatCode/RatPoison#712]
My game crashes when I join the match with RatPoison 1.8.I tried opening it before opening CS GO,after opening CS GO,before loading into the game,after loading into the game,still crashes.Tried reinstalling RatPoison and Verifying CS GO.Still nothing

**Comment by monkeyscout** [comment]
Just wait for an update, other pips are experiencing it too.

**Comment by DenixxBTW** [comment]
> Just wait for an update, other pips are experiencing it too.

Not even 1.7 works anymore :(((
