### ISSUE TITLE
Rat Crash Issue

### ISSUE THREAD

**Issue by BigSillyWill69** [TheRatCode/RatPoison#713]
Everytime Inferno is launched, csgo crashes

**Comment by BigSillyWill69** [comment]
Edit: Used to work when i was playing nuke/office/mirage, I launched it and it was fine on the main menu, but when I got into an inferno game csgo crashed, now it only works on the main menu, and going into any game makes csgo crash

**Comment by sotakoira** [comment]
[this](https://github.com/Akandesh/blazedumper) hasn't been updated for ages, I suggest redownloading from GitHub as offset repository has been changed.
