### ISSUE TITLE
[BUG] HandleFireKey shoots through open console and steam overlay

### ISSUE THREAD

**Issue by sotakoira** [TheRatCode/RatPoison#716]
**Describe the bug**

Since the introduction of HandleFireKey.kt (11th July 2020) RatPoison shoots through certain cursor enabled windows like console or steam overlay. CursorEnable check doesn't work for them.

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

Load any config with write aim aimbot.
Open console, press left mouse button.
Close console, press Shift+Tab, press left mouse button.

Same goes for bunnyhop or anything using dwForceAttack.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

https://user-images.githubusercontent.com/63243610/105910691-984c6080-6029-11eb-89bc-ab8ccdafc6f8.mp4

**Comment by SPRAVEDLIVO** [comment]
iirc, this was fixed in alpha

**Comment by sotakoira** [comment]
> iirc, this was fixed in alpha 

this was recorded in alpha 1.8.6

**Comment by sotakoira** [comment]
https://user-images.githubusercontent.com/63243610/112201344-70840e00-8c10-11eb-9386-80852279ccdd.mp4
