### ISSUE TITLE
Menu not opening.

### ISSUE THREAD

**Issue by rislaxd** [TheRatCode/RatPoison#718]
Always when i press f1 while in game, csgo throws me out of the game, it doesn't close the game it just gets me to the desktop and mod menu doesn't open up.

I have java 12 installed and in use.
i have turned debugging on.
i have reinstalled cheats multiple times.

I have tried everything i've seen here but nothing seems to work.

**Comment by sotakoira** [comment]
you aren't in fullscreen windowed mode.

**Comment by SPRAVEDLIVO** [comment]
This seems to be resolved
