### ISSUE TITLE
Compilation error, :compileKotlin failed

### ISSUE THREAD

**Issue by Liittyipeliin** [TheRatCode/RatPoison#719]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
1 actionable task: 1 executed

JDK Version: jdk1.8.0_211

**Comment by sotakoira** [comment]
no logs, installer and releases install/come with jdk 14.0.2, not enough info

**Comment by Liittyipeliin** [comment]
Logs: https://pastebin.com/UNK4h9NK

**Comment by SPRAVEDLIVO** [comment]
https://github.com/TheRatCode/RatPoison/releases
