### ISSUE TITLE
aimbot fov[BUG]

### ISSUE THREAD

**Issue by skedaddl** [TheRatCode/RatPoison#721]
whenever i make the aimbot fov over 5, the aimbot likes to snap around instead of aiming at the right thing

set aimbot fov above 5 and hold your force aimbot and shoot some enemies

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

**Comment by SPRAVEDLIVO** [comment]
cfg issue

**Comment by skedaddl** [comment]
ah ok
