### ISSUE TITLE
[BUG] Chams issue

### ISSUE THREAD

**Issue by kmail960** [TheRatCode/RatPoison#723]
Chams apply to yourself even if you have self-chams off.

![image](https://user-images.githubusercontent.com/63985330/108085438-52d8ed00-7043-11eb-89ca-4e6d80963cc2.png)

--------------

A user already posted this 3 days ago but closed it right after, so I'm reposting it for him.

I've had this issue for a while and It's the reason why I don't use chams

**Comment by uwuLegacy** [comment]
uid issue

/closed

**Comment by kmail960** [comment]
dhfbgdfg wtf

**Comment by thefuckingrap** [comment]
set chams brightness to 0 🧨
