### ISSUE TITLE
[BUG] Switching weapons lag since today's update.

### ISSUE THREAD

**Issue by sotakoira** [TheRatCode/RatPoison#724]
**Describe the bug**

Switching weapons and shooting is laggy and often fails on online servers.
Happened with [2/17/2021](https://blog.counter-strike.net/index.php/2021/02/33160/) update.

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

Queue into Valve DM and switch weapons.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

https://user-images.githubusercontent.com/63243610/108310451-b08c4700-71b3-11eb-8299-0a9b60d56afa.mp4

**Comment by satyampanchal** [comment]
having same issue

**Comment by sotakoira** [comment]
Alpha branch does not have this issue, same with the [infamous 4th june build](https://github.com/TheRatCode/RatPoison/tree/b4fdebb29a0e45239c8021d5250b9db107de7178).

**Comment by sotakoira** [comment]
[Seems to be fixed now.](https://github.com/frk1/hazedumper/commit/3fcf5d49fca0cd0edb69d802773923deac881abb)

**Comment by adamwearingatophat** [comment]
how do i use that fix?

**Comment by sotakoira** [comment]
> 
> 
> how do i use that fix?

Just make sure your ParseOffset.kt uses hazedumper repo.
https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt#L8

**Comment by adamwearingatophat** [comment]
> > how do i use that fix?
> 
> Just make sure your ParseOffset.kt uses hazedumper repo.
> https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt

> > how do i use that fix?
> 
> Just make sure your ParseOffset.kt uses hazedumper repo.
> https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt#L8

i copy pasted the code from that link into the parseoffset.kt file and i still have the stuttering sometimes when changing weapons

**Comment by sotakoira** [comment]
> 
> 
> > > how do i use that fix?
> > 
> > 
> > Just make sure your ParseOffset.kt uses hazedumper repo.
> > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt
> 
> > > how do i use that fix?
> > 
> > 
> > Just make sure your ParseOffset.kt uses hazedumper repo.
> > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt#L8
> 
> i copy pasted the code from that link into the parseoffset.kt file and i still have the stuttering sometimes when changing weapons

enable debug and check if console spews this https://i.imgur.com/IVcjUIW.png
if you have a different number then you havent done this properly

**Comment by Cereal98** [comment]
> > > > how do i use that fix?
> > > 
> > > 
> > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt
> > 
> > 
> > > > how do i use that fix?
> > > 
> > > 
> > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt#L8
> > 
> > 
> > i copy pasted the code from that link into the parseoffset.kt file and i still have the stuttering sometimes when changing weapons
> 
> enable debug and check if console spews this https://i.imgur.com/IVcjUIW.png
> if you have a different number then you havent done this properly

Well, attempt from different person, this didn't work

**Comment by adamwearingatophat** [comment]
> > > > how do i use that fix?
> > > 
> > > 
> > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt
> > 
> > 
> > > > how do i use that fix?
> > > 
> > > 
> > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt#L8
> > 
> > 
> > i copy pasted the code from that link into the parseoffset.kt file and i still have the stuttering sometimes when changing weapons
> 
> enable debug and check if console spews this https://i.imgur.com/IVcjUIW.png
> if you have a different number then you havent done this properly

i cant find where that number should apppear, i turn on the debug thats in the menu right?

**Comment by sotakoira** [comment]
> 
> 
> > > > > how do i use that fix?
> > > > 
> > > > 
> > > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt
> > > 
> > > 
> > > > > how do i use that fix?
> > > > 
> > > > 
> > > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt#L8
> > > 
> > > 
> > > i copy pasted the code from that link into the parseoffset.kt file and i still have the stuttering sometimes when changing weapons
> > 
> > 
> > enable debug and check if console spews this https://i.imgur.com/IVcjUIW.png
> > if you have a different number then you havent done this properly
> 
> Well, attempt from different person, this didn't work

make sure you did whatever was shown or have up-to-date beta.
https://github.com/TheRatCode/RatPoison/releases/download/1.8.4.1/RatPoison-1.8.4.1.zip

**Comment by Cereal98** [comment]
> > > > > > how do i use that fix?
> > > > > 
> > > > > 
> > > > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt
> > > > 
> > > > 
> > > > > > how do i use that fix?
> > > > > 
> > > > > 
> > > > > Just make sure your ParseOffset.kt uses hazedumper repo.
> > > > > https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/utils/ParseOffset.kt#L8
> > > > 
> > > > 
> > > > i copy pasted the code from that link into the parseoffset.kt file and i still have the stuttering sometimes when changing weapons
> > > 
> > > 
> > > enable debug and check if console spews this https://i.imgur.com/IVcjUIW.png
> > > if you have a different number then you havent done this properly
> > 
> > 
> > Well, attempt from different person, this didn't work
> 
> make sure you did whatever was shown or have up-to-date beta.
> https://github.com/TheRatCode/RatPoison/releases/download/1.8.4.1/RatPoison-1.8.4.1.zip

Yep, everything works fine with this beta, thank you ;)

**Comment by Renanx70** [comment]
could someone please record a tutorial for me on how to fix the bug?
