### ISSUE TITLE
[BUG] My dropout menus are closing when i click on them so i cant change guns and hitboxes. But its only in the aim section.

### ISSUE THREAD

**Issue by Userofthcheat** [TheRatCode/RatPoison#725]
**Describe the bug**

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

**Comment by sotakoira** [comment]
wheres the video

**Comment by 9191929992** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.
> 
> **Pictures/Videos**
> If applicable, add screenshots or link a video to help explain your problem.

Video?

**Comment by SPRAVEDLIVO** [comment]
what

**Comment by 9191929992** [comment]
> what

i don't know.

**Comment by SPRAVEDLIVO** [comment]
do you know what video means?
we need to make sure this bug actually exists

**Comment by arf25** [comment]
I can confirm I am having the same issue, but i do not have a good way to record. Unable to switch guns and the games acts very funny.

**Comment by sotakoira** [comment]
> I can confirm I am having the same issue, but i do not have a good way to record. Unable to switch guns and the games acts very funny.

Update to the newest version. Your dwbSendPackets offset is not correct and this time instead of straight up crashing guns don't switch properly.

**Comment by SPRAVEDLIVO** [comment]
> > I can confirm I am having the same issue, but i do not have a good way to record. Unable to switch guns and the games acts very funny.
> 
> Update to the newest version. Your dwbSendPackets offset is not correct and this time instead of straight up crashing guns don't switch properly.

That is not the same issue from the description
