### ISSUE TITLE
[BUG] None of the menu options or ESP applying?

### ISSUE THREAD

**Issue by amongusistrash** [TheRatCode/RatPoison#742]
So when I press any of the menu buttons, literally nothing happens. I'm running CSGO in windowed fullscreen and everything, but nothing seems to happen. If I switch on ESP, no ESP. Aimbot? No aimbot. Skin changer? Nothing happens. So i have no idea what to do, because older versions worked for me.

**Comment by SPRAVEDLIVO** [comment]
send video demonstration and drop your config here

**Comment by thefuckingrap** [comment]
My cat died

**Comment by sotakoira** [comment]
> 
> 
> So when I press any of the menu buttons, literally nothing happens. I'm running CSGO in windowed fullscreen and everything, but nothing seems to happen. If I switch on ESP, no ESP. Aimbot? No aimbot. Skin changer? Nothing happens. So i have no idea what to do, because older versions worked for me.

amogus
