### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wuxez** [TheRatCode/RatPoison#747]
When i try to open the cheat, the menu just dosent load!Can someone help?

**Comment by SPRAVEDLIVO** [comment]
https://cdn.discordapp.com/attachments/785832919234117643/823868594156077096/soos.gif

**Comment by Jasmitt** [comment]
pc issue, need to reset all files sorry man factory reset pc

**Comment by sotakoira** [comment]
works as always https://cdn.discordapp.com/attachments/822949193035415612/825013214793695262/works2.mp4

**Comment by wuxez** [comment]
Just reinstall JDK ez fix
