### ISSUE TITLE
Installer.exe file disappears

### ISSUE THREAD

**Issue by XotomasaM** [TheRatCode/RatPoison#748]
**Describe the bug**
After installing the zip file and extracting it, the installer.exe file is automatically deleted before it can be opened

**To Reproduce**
1.Install zip folder
2. extract folder
3. open installer.exe file 
4. watch it disappear

I believe this may have something to do with Bitdefender deleting the file.

**Comment by sotakoira** [comment]
your antivirus deletes it, not an issue with the installer.

**Comment by SPRAVEDLIVO** [comment]
so excited

**Comment by XotomasaM** [comment]
Thanks a lot @sotakoira

**Comment by 9191929992** [comment]
Pog
