### ISSUE TITLE
Error while opening bat file

### ISSUE THREAD

**Issue by fassanito** [TheRatCode/RatPoison#758]
I'm new in cheating in cs go and i wanted to use ratpoison but unlucky  while turning on bat file the following error appears: ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context. How to repair that?

**Comment by sotakoira** [comment]
https://github.com/TheRatCode/RatPoison/issues/754
https://github.com/TheRatCode/RatPoison/issues/629
https://github.com/TheRatCode/RatPoison/issues/304

tldr get a better pc

**Comment by fassanito** [comment]
> #754
> #629
> #304
> 
> tldr get a better pc

But why? My gpu supports up to 4.4 opengl version

**Comment by sotakoira** [comment]
basically
- laptop user that doesnt use dedicated gpu on java.exe
- pc with amd gpu

**Comment by thefuckingrap** [comment]
pov u are a snake
