### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Auroraaaaaaaa** [TheRatCode/RatPoison#763]
**Describe the bug**
Crashes as soon as the loading bar is at the end when loading in to a game

**To Reproduce**
Launch CSGO and RatPoison, Load into a game then screen turn back and can not be closed without command prompt being closed

**Pictures/Videos**
![Desktop Screenshot 2021 05 03 - 20 09 48 54](https://user-images.githubusercontent.com/83619949/116947894-e8037f00-ac4b-11eb-8432-362c4e2ba586.png)

**Comment by sotakoira** [comment]
csgo update happened, wait for hazedumper or override dwbsendpackets yourself
