### ISSUE TITLE
hazedumper

### ISSUE THREAD

**Issue by lilwhessie** [TheRatCode/RatPoison#764]
what i have to do with hazedumper now? Where should i change/edit? can someone explain with little bit detail please thanks

**Comment by sotakoira** [comment]
use beta like a normal person

**Comment by sotakoira** [comment]
RatPoison/src/main/kotlin/rat/poison/utils/ParseOffset.kt

Replace `val connection = URL("https://raw.githubusercontent.com/JokinAce/CSGO-Offsets/master/csgo.json")`
with `val connection = URL("https://raw.githubusercontent.com/frk1/hazedumper/master/csgo.json")`

Delete build folder, recompile.

**Comment by lilwhessie** [comment]
> use beta like a normal person

if you talking about ratpoison 1.7.1.2 it also crashing i dont know why

**Comment by sotakoira** [comment]
> if you talking about ratpoison 1.7.1.2 it also crashing i dont know why

talking about beta, so 1.8.5.5

**Comment by SukhiRitesh** [comment]
Where can I download beta, 1.8.5.5

**Comment by SukhiRitesh** [comment]
So here is the thing, I just downloaded ratpoison 1.7 yesterday. Played a while
But as today CS GO got updated the game kept crashing when I was about to start a match with ratpoison on in the background

Now if beta, 1.8.5.5 can help then its going to be awesome.

If not, then what to do with 1.7 version.

**Comment by sotakoira** [comment]
![firefox_2021-05-04_13-30-13](https://user-images.githubusercontent.com/63243610/116997378-01084080-acdd-11eb-9974-80c167ed74a8.png)

![firefox_2021-05-04_13-31-44](https://user-images.githubusercontent.com/63243610/116997474-209f6900-acdd-11eb-9236-d899f579ce1a.png)

If yall cant follow this i have bad news: get osiris instead

**Comment by lilwhessie** [comment]
thanks for all the help <3
