### ISSUE TITLE
Ratpoison beta 1.8.5.5 crashes

### ISSUE THREAD

**Issue by Blob972** [TheRatCode/RatPoison#768]
Hi guys, 

Last night an update on cs go was pulled on. This had the consequence of blocking the functioning of the cheat. Is this bug related to me or is it a known issue ?

It is really simple to reproduce : I start the game, then i run the cheat, then the game closes. The overlay that normally appears on my desktop does not appear anymore. There is no weird errors that are mentionned on the cheat console.

Do I have to wait for updates or is this a problem that I might resolve by myself ?

Thanks a lot,

**Comment by sotakoira** [comment]
beta doesnt crash anymore, been fixed for 2 hours already

**Comment by Blob972** [comment]
Do I have to rebuild the cheat or put any update on it ? 

Thanks a lot

**Comment by sotakoira** [comment]
if you are using latest beta no

**Comment by Blob972** [comment]
Thanks a lot it is working :)

**Comment by akototanga** [comment]
can you please help me. i downloaded beta version of like what u instruct in previous thread and console ask me where id put the JDK file so when i tracked it and set where i find the jdk folder its constantly says that build if failed? is this gonna affect the code itself or should i just continue and ignore downloading new jdk?

**Comment by Blob972** [comment]
I think u have to put JDK in a new folder that will be used to build RP, i'm not sure. I have a folder with JDK folder inside, and RP folder.

**Comment by sotakoira** [comment]
use this if you need guidance on how to use a personal computer https://github.com/TheRatCode/RatPoison/releases/download/1.8.5.5/RatPoison-1.8.5.5.zip
unpack to a folder, run start ratpoison bat when game is running

**Comment by SukhiRitesh** [comment]
My humble apologies but it is still not working

**Comment by sotakoira** [comment]
> My humble apologies but it is still not working

runs fine for me and others

**Comment by SukhiRitesh** [comment]
After waiting for Counter Strike it says:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation

Game Found. Launching.
Waiting for App
Initializing Overlay
Overlay initialized.


Nothing happens after this.
I tried to start a match as well, match started but ratpoison wont work.

**Comment by akototanga** [comment]
so apperantly after a few minutes of my exploring on how to. whenever it asks about where to put your JDK folder its should be what Drive u use to download your files. in my case use to 2 different storage though an ssd and a hdd (where i use to save my downloaded file), so i put it in hdd and then it continued to build until up to finish. now i can test this if this will run smoothly without getting disconnected or anything. thanks for the help guys. cheers!

**Comment by Blob972** [comment]
Ok i think i know why it is not working : to initialize the overlay u must be in 16/9 resolution. If u play in 4/3 resolution u have to modify a file.

Go to build>RatPoison 1.8>Settings>General

On general text file u change at the end 
//Appless settings
APPLESS = true 

By doing it your overlay will initialize on your desktop.

**Comment by Blob972** [comment]
For this : 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation

I have the same on my console but the cheat still work properly.

**Comment by sotakoira** [comment]
Title is clearly saying "crashes". Running the cheat in 4:3 won't crash anything, just prevents you from accessing the menu until switched to windowed mode.

**Comment by Blob972** [comment]
ye but he said : 

"After waiting for Counter Strike it says:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation

Game Found. Launching.
Waiting for App
Initializing Overlay
Overlay initialized."

If he has that, his game must be working while using RP so i thought prob wasnt about crash but about the overlay.

**Comment by sotakoira** [comment]
slf4j "error" does nothing. you can ignore it

**Comment by SukhiRitesh** [comment]
Everything works fine, thank you guys. 
I just need to ask a small favor could you direct me to configs of RatPoison Master, I am a little habitual to them.

And Thank you for helping
