### ISSUE TITLE
what is head level helper????[QUESTION]

### ISSUE THREAD

**Issue by mountaincastle47** [TheRatCode/RatPoison#770]
**Ask questions**
Ask any questions related to the project
how to use it and what does it do?

**Comment by sotakoira** [comment]
helps you have your crosshair always at head level

**Comment by mountaincastle47** [comment]
> helps you have your crosshair always at head level

and uh what is headlvldeadzone? and headlvllinewidth?

**Comment by sotakoira** [comment]
just test it, keep deadzone at lowest possible lol

**Comment by mountaincastle47** [comment]
> just test it, keep deadzone at lowest possible lol

ty
