### ISSUE TITLE
cfg for recording?[QUESTION]

### ISSUE THREAD

**Issue by mountaincastle47** [TheRatCode/RatPoison#771]
i wanna show it to my friend and say "bam it was cheat all along"

**Comment by sotakoira** [comment]
read license about warranty and liability

**Comment by mountaincastle47** [comment]
> read license about warranty and liability

uh i am bad at english can you give me a point

**Comment by sotakoira** [comment]
https://github.com/TheRatCode/RatPoison/blob/master/LICENSE.txt#L587-L608

**Comment by mountaincastle47** [comment]
> https://github.com/TheRatCode/RatPoison/blob/master/LICENSE.txt#L587-L608

ty
