### ISSUE TITLE
csgo has been upadated again  [BUG]

### ISSUE THREAD

**Issue by mountaincastle47** [TheRatCode/RatPoison#773]
**Describe the bug**

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

**Comment by Zayoe4** [comment]
Game crashes every time there is a change.

**Comment by sotakoira** [comment]
dwbsendpackets probably outdated again, i dont quite understand people reporting this

**Comment by sotakoira** [comment]
temp fix, still better to wait until morning for hazedumper to update

https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt#L17

change this to `val dwbSendPackets = 882394`

delete build folder, recompile.

**Comment by thefuckingrap** [comment]
we could (and should) date.

**Comment by whatsupdawg11** [comment]
yo how do u do the dwbsendpackets thing can anyone explain rq? i went to the file destination and i cant do anything w it

**Comment by sotakoira** [comment]
> yo how do u do the dwbsendpackets thing can anyone explain rq? i went to the file destination and i cant do anything w it

you are capping. https://streamable.com/cuohev

**Comment by whatsupdawg11** [comment]
> > yo how do u do the dwbsendpackets thing can anyone explain rq? i went to the file destination and i cant do anything w it
> 
> you are capping. https://streamable.com/cuohev

How do you get it to show as a .txt file?

**Comment by sotakoira** [comment]
> How do you get it to show as a .txt file? Mine is .kt

same for me. just open the bitch in notepad or any other file editor

**Comment by hrithik-r** [comment]
> temp fix, still better to wait until morning for hazedumper to update
> 
> https://github.com/TheRatCode/RatPoison/blob/beta/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt#L17
> 
> change this to `val dwbSendPackets = 882394`
> 
> delete build folder, recompile.

This didn't change anything. It's still crashing

**Comment by sotakoira** [comment]
> This didn't change anything. It's still crashing

https://i.imgur.com/d2Wwnd5.png

**Comment by sotakoira** [comment]
https://github.com/frk1/hazedumper/commit/04deef52783a3a54f8e6af334d236d751b40ff3b
hazedumper updated, close this please

**Comment by SukhiRitesh** [comment]
How to connect to hazedumper?
And are the changes made for master 1.7 version as well?

**Comment by SukhiRitesh** [comment]
And I am facing a new problem when I press Insert key to access menu. The game minimizes what is that all about?

**Comment by hrithik-r** [comment]
> > This didn't change anything. It's still crashing
> 
> https://i.imgur.com/d2Wwnd5.png

I meant its working but its crashing mid game always :/

**Comment by sotakoira** [comment]
> I meant its working but its crashing mid game always :/

https://i.imgur.com/wOIAtcd.png

**Comment by hrithik-r** [comment]
Then 

> > I meant its working but its crashing mid game always :/
> 
> https://i.imgur.com/wOIAtcd.png

Ok, then there's issue on my side. Thanks

**Comment by SukhiRitesh** [comment]
Working fine
