### ISSUE TITLE
[QUESTION] AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by kuresfunk** [TheRatCode/RatPoison#775]
Guys, when i try to launch the cheat i always get this error in console and the game crashes. I couldnt find any sollution for this problem on the internet. Can anybody help me with this?

AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by SPRAVEDLIVO** [comment]
this happens because of outdated dwbsendpackets
i assume you are using master branch
update to beta

**Comment by kuresfunk** [comment]
Oh, okay i fixed it. Tysm !

**Comment by Zwillyzz** [comment]
On the latest beta, I'm getting this "AL lib: (EE) alc_cleanup: 1 device not closed" error randomly after a match is done.
