### ISSUE TITLE
Not installing?~

### ISSUE THREAD

**Issue by codyxd** [TheRatCode/RatPoison#776]
Earlier, Ratpoison used to install.
But after yesterdays update, when it stopped working, I had deleted the folder and the zip.
Re-downloaded it today but now its just not installing.
It shows me the following errors.
What to do?
I dunno how to run cmd or I can't code and whatnot either.
![error 1](https://user-images.githubusercontent.com/47775604/117452262-2dcc8a00-af61-11eb-9f90-603007b158b1.png)
![error 2](https://user-images.githubusercontent.com/47775604/117452269-2f964d80-af61-11eb-8e95-3a655719bf7a.png)

**Comment by SPRAVEDLIVO** [comment]
@actions
@releases

**Comment by sotakoira** [comment]
use https://github.com/TheRatCode/RatPoison/releases or ask spravedlivo to fix installer

**Comment by codyxd** [comment]
@sotakoira Heya, thank you for that release. Unfortunately, the overlay showing up when i press f1.
@SPRAVEDLIVO sir can you kindly fix the installer please?;-;

**Comment by codyxd** [comment]
![loop](https://user-images.githubusercontent.com/47775604/117454903-3e323400-af64-11eb-97df-ac25b6b333b1.png)

**Comment by SPRAVEDLIVO** [comment]
not possible to fix
