### ISSUE TITLE
GLFW Version unavailable Error..

### ISSUE THREAD

**Issue by codyxd** [TheRatCode/RatPoison#777]
So, i was teaching my friend how to use ratpoison. Windowed mode check. Everything done. He was getting this error. 
What can be done?
![3406122 2150000003_image](https://user-images.githubusercontent.com/47775604/117533040-1a282e80-b008-11eb-9a09-d8a0f754e75a.png)

**Comment by sotakoira** [comment]
https://github.com/TheRatCode/RatPoison/blob/master/settings/OpenGL.txt#L13
this to false
